# nix/gen-constants.nix
#
# Renders nix/constants.nix into the Rust source for
# `crates/agent-grpc/src/constants.rs`, formatted with the pinned `rustfmt` so the
# result passes the rustfmt check verbatim.
#
# Returns a single derivation (the formatted file). Both the `gen-constants` app
# (which copies it into the repo) and the `constants-sync` check (which diffs it
# against the committed file) reference THIS derivation, so they can never disagree.
{ pkgs, versions }:
let
  c = import ./constants.nix;
  g = c.grpc;

  seamConst =
    name: s:
    "pub const ${name}: SeamEndpoint = SeamEndpoint { tcp_port: ${toString s.port}, uds_path: \"${s.socket}\", metrics_port: ${toString s.metrics_port} };";

  raw = ''
    // @generated by `nix run .#gen-constants` from nix/constants.nix — DO NOT EDIT.
    //
    // Per-seam default gRPC endpoints: a unique loopback TCP port and a
    // unix-domain-socket path. `nix/constants.nix` is the single source of truth;
    // regenerate after editing it (`nix run .#gen-constants`). The `constants-sync`
    // flake check fails if this file drifts.

    /// A seam's default gRPC listen endpoints.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct SeamEndpoint {
        /// Loopback TCP port, for cross-process / cross-host use.
        pub tcp_port: u16,
        /// Unix-domain-socket path, for same-host TCP-bypassing use.
        pub uds_path: &'static str,
        /// Loopback Prometheus `/metrics` port used when this seam runs as its own
        /// `agent --serve-<seam>` process (so co-located seam servers don't collide).
        pub metrics_port: u16,
    }

    /// Directory holding the per-seam unix domain sockets.
    pub const SOCKET_DIR: &str = "${c.socketDir}";

    ${seamConst "PROVIDER" g.provider}
    ${seamConst "MEMORY" g.memory}
    ${seamConst "TOOLS" g.tools}
    ${seamConst "CONTEXT" g.context}
    ${seamConst "POLICY" g.policy}
    ${seamConst "SEARCH" g.search}
    ${seamConst "REPO" g.repo}
    ${seamConst "SESSION" g.session}
    ${seamConst "SCANNER" g.scanner}
    ${seamConst "REFERENCE" g.reference}
    ${seamConst "SCHEDULER" g.scheduler}
    ${seamConst "TOKENIZER" g.tokenizer}
    ${seamConst "EMBED" g.embed}
    ${seamConst "WEB" g.web}
    ${seamConst "WEB_SEARCH" g.web_search}
    ${seamConst "SANDBOX" g.sandbox}
    ${seamConst "PTY" g.pty}
    ${seamConst "FORGE" g.forge}
    ${seamConst "TASKS" g.tasks}
    ${seamConst "LSP" g.lsp}
    ${seamConst "EPISODIC" g.episodic}
    ${seamConst "SEMANTIC" g.semantic}
    ${seamConst "LLM_POOL" g.llm_pool}
    ${seamConst "REVIEW" g.review}

    /// The `agent --serve-all` gateway (not a seam — it hosts every seam).
    ${seamConst "GATEWAY" g.gateway}
  '';

  rawFile = pkgs.writeText "agent-grpc-constants-raw.rs" raw;
in
pkgs.runCommand "agent-grpc-constants.rs" { nativeBuildInputs = [ versions.rustToolchain ]; } ''
  cp ${rawFile} out.rs
  chmod u+w out.rs
  rustfmt --edition 2021 out.rs
  cp out.rs $out
''
