-- agent-campaign schema (docs/design/campaigns/01-schema.md): one `tasks` tree
-- table (materialized path, depth <= 6, ordinal 1..8) and two append-only audit
-- tables, `task_events` and `task_attempts`. Applied exactly once by the versioned
-- runner in `postgres.rs` (`PgCampaigns::run_migrations`).
--
-- Deviations from the design listing, all deliberate:
--   * `CREATE TABLE / INDEX IF NOT EXISTS` throughout, so a DB carrying the schema
--     but no ledger re-records this baseline harmlessly (digest / config-store
--     precedent).
--   * the UNIQUE constraints are NAMED (`tasks_path_key`, `task_attempts_idem_key`)
--     so the store maps a violation by constraint name, never by message text.
--   * `tenants` is exactly the config-store definition (`0001_config_store.sql`);
--     whichever runner comes first creates it and the other finds it. Any suite
--     that TRUNCATEs `tenants` must now CASCADE (the three tables reference it).
--   * `repo_id` is a plain BIGINT until the repo-knowledge `repos` table lands
--     (RK-02); the conditional block at the end adds the FK once it exists.
-- Every id / tenant reaches SQL as a bound parameter; the CHECKs are the storage
-- grammar, the app-side rules (`agent_core::campaign`) are checked before them.

CREATE TABLE IF NOT EXISTS tenants (
    tenant TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS tasks (
  tenant        TEXT        NOT NULL REFERENCES tenants(tenant),
  task_id       BIGINT      GENERATED BY DEFAULT AS IDENTITY,
  campaign_id   BIGINT      NOT NULL,                 -- the root's task_id; on the root = task_id
  repo_id       BIGINT      NOT NULL,                 -- FK to repos(tenant, repo_id) once RK-02 lands
  parent_id     BIGINT,                               -- NULL iff depth = 0
  path          TEXT        NOT NULL,                 -- '1042' | '1042.1' | '1042.1.3'
  depth         SMALLINT    NOT NULL CHECK (depth BETWEEN 0 AND 6),
  ordinal       SMALLINT    NOT NULL CHECK (ordinal BETWEEN 1 AND 8),
  kind          TEXT        NOT NULL CHECK (kind IN ('objective', 'task', 'leaf')),
  state         TEXT        NOT NULL CHECK (state IN (
                  'draft', 'awaiting_approval', 'ready', 'decomposing', 'decomposed',
                  'claimed', 'running', 'in_review', 'blocked', 'done', 'failed',
                  'cancelled', 'superseded')),
  title         TEXT        NOT NULL CHECK (length(title) BETWEEN 1 AND 120),
  goal          TEXT        NOT NULL CHECK (length(goal) BETWEEN 1 AND 4000),
  acceptance    JSONB       NOT NULL DEFAULT '[]',    -- <= 6 strings, each <= 300 chars (app-side)
  touches       JSONB       NOT NULL DEFAULT '[]',    -- <= 12 node_keys or repo paths (app-side)
  depends_on    BIGINT[]    NOT NULL DEFAULT '{}',    -- sibling task_ids; acyclic (app-side)
  est_size      TEXT        CHECK (est_size IN ('xs', 's', 'm', 'l')),
  source_ref    TEXT        CHECK (source_ref IS NULL OR length(source_ref) <= 120),
  policy        JSONB       CHECK (policy IS NULL OR depth = 0),
  version       BIGINT      NOT NULL DEFAULT 1,
  attempts      SMALLINT    NOT NULL DEFAULT 0,       -- planner attempts on this node
  claimed_by    TEXT,                                 -- driver owner token while claimed / running
  lease_until   TIMESTAMPTZ,
  pr_number     BIGINT,
  pr_url        TEXT        CHECK (pr_url IS NULL OR length(pr_url) <= 512),
  branch        TEXT        CHECK (branch IS NULL OR length(branch) <= 128),
  superseded_by BIGINT,
  created_by    TEXT        NOT NULL,                 -- 'user:<principal>' | 'model:<attempt_id>'
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant, task_id),
  FOREIGN KEY (tenant, parent_id)   REFERENCES tasks (tenant, task_id),
  FOREIGN KEY (tenant, campaign_id) REFERENCES tasks (tenant, task_id) DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT tasks_path_key UNIQUE (tenant, path),
  CHECK ((depth = 0) = (parent_id IS NULL)),
  CHECK (path ~ '^[1-9][0-9]*(\.[1-8]){0,6}$'),
  CHECK (array_length(string_to_array(path, '.'), 1) = depth + 1),
  CHECK ((state IN ('claimed', 'running')) = (claimed_by IS NOT NULL)),
  CHECK ((state IN ('claimed', 'running')) = (lease_until IS NOT NULL)),
  CHECK (kind <> 'objective' OR depth = 0),
  CHECK (depth <> 0 OR kind = 'objective'),
  CHECK (depth <> 0 OR campaign_id = task_id),
  CHECK (superseded_by IS NULL OR state = 'superseded')
);

CREATE INDEX IF NOT EXISTS tasks_subtree  ON tasks (tenant, path text_pattern_ops);
CREATE INDEX IF NOT EXISTS tasks_ready    ON tasks (tenant, repo_id, campaign_id, path)
  WHERE state = 'ready' AND kind = 'leaf';
CREATE INDEX IF NOT EXISTS tasks_plan     ON tasks (tenant, campaign_id, path)
  WHERE state = 'ready' AND kind <> 'leaf';
CREATE INDEX IF NOT EXISTS tasks_lease    ON tasks (tenant, lease_until) WHERE claimed_by IS NOT NULL;
CREATE INDEX IF NOT EXISTS tasks_review   ON tasks (tenant, updated_at) WHERE state = 'in_review';
CREATE INDEX IF NOT EXISTS tasks_parent   ON tasks (tenant, parent_id);
CREATE INDEX IF NOT EXISTS tasks_campaign ON tasks (tenant, campaign_id);

CREATE TABLE IF NOT EXISTS task_events (
  tenant     TEXT        NOT NULL REFERENCES tenants(tenant),
  event_id   BIGINT      GENERATED ALWAYS AS IDENTITY,
  task_id    BIGINT      NOT NULL,
  from_state TEXT,                                    -- NULL on creation
  to_state   TEXT        NOT NULL,
  actor      TEXT        NOT NULL,                    -- 'user:<p>' | 'driver:<owner>' | 'model:<attempt>' | 'reaper' | 'poller' | 'rollup'
  version    BIGINT      NOT NULL,                    -- tasks.version after the write
  detail     JSONB       NOT NULL DEFAULT '{}' CHECK (pg_column_size(detail) <= 4096),
  at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant, event_id),
  FOREIGN KEY (tenant, task_id) REFERENCES tasks (tenant, task_id)
);
CREATE INDEX IF NOT EXISTS task_events_task ON task_events (tenant, task_id, event_id);

CREATE TABLE IF NOT EXISTS task_attempts (
  tenant      TEXT        NOT NULL REFERENCES tenants(tenant),
  attempt_id  BIGINT      GENERATED ALWAYS AS IDENTITY,
  task_id     BIGINT      NOT NULL,
  kind        TEXT        NOT NULL CHECK (kind IN ('decompose', 'work')),
  idem_key    TEXT        NOT NULL CHECK (length(idem_key) = 64),  -- hex sha256
  prompt_hash TEXT        NOT NULL DEFAULT '',
  model       TEXT        NOT NULL DEFAULT '',
  tokens_in   BIGINT      NOT NULL DEFAULT 0 CHECK (tokens_in >= 0),
  tokens_out  BIGINT      NOT NULL DEFAULT 0 CHECK (tokens_out >= 0),
  session_id  TEXT,
  owner       TEXT,                                   -- driver owner token for kind = 'work'
  outcome     TEXT        NOT NULL CHECK (outcome IN (
                'pending', 'execute', 'split', 'needs_info', 'reject',
                'pr', 'error', 'timeout', 'lease_lost')),
  pr_url      TEXT        CHECK (pr_url IS NULL OR length(pr_url) <= 512),
  error       TEXT        CHECK (error IS NULL OR length(error) <= 2000),
  started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at    TIMESTAMPTZ,
  PRIMARY KEY (tenant, attempt_id),
  CONSTRAINT task_attempts_idem_key UNIQUE (tenant, idem_key),
  FOREIGN KEY (tenant, task_id) REFERENCES tasks (tenant, task_id)
);
CREATE INDEX IF NOT EXISTS task_attempts_task ON task_attempts (tenant, task_id, attempt_id);

-- Conditional FK to the repo-knowledge `repos` table (RK-02). The migration is
-- re-runnable: the constraint is added once `repos` exists and skipped otherwise.
DO $$
BEGIN
  IF to_regclass('repos') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'tasks_repo_fk') THEN
    ALTER TABLE tasks ADD CONSTRAINT tasks_repo_fk
      FOREIGN KEY (tenant, repo_id) REFERENCES repos (tenant, repo_id);
  END IF;
END $$;
