#!/usr/bin/env python3
"""ClickHouse credentials for the agent's dev/l2 ClickHouse (security-hardening S16).

One directory holds one password file per login, each 0600 in a 0700 directory:

    admin.password    the `default` user: schema apply, access management, the OTel
                      collector (which creates its own otel_* tables)
    writer.password   agent_writer: the agent's telemetry writer + digest store
    reader.password   agent_reader: the tenant-scoped reader (`[telemetry] reader_user`)
    viewer.password   agent_viewer: read-only dashboards (HyperDX app, Grafana)

and one rendered server override, `server/50-agent-credentials.xml`, holding only the
SHA-256 of the admin password, which `clickhouse-up` bind-mounts into users.d.

The directory defaults to $AGENT_CLICKHOUSE_SECRETS, else
$XDG_STATE_HOME/agent-seddon/clickhouse (~/.local/state/...). It is persistent state,
not tmpfs: the container keeps the admin hash across restarts, so the file must too.

Subcommands:

    ensure                 create any missing password (never overwrites one) and
                           (re)render the server override; refuses a directory or
                           file readable by group/other, or a malformed password
    path ROLE              print a password file's path (ROLE = admin|writer|reader|
                           viewer), or `server-xml` for the override
    alter-sql              print the ALTER USER statements that set the three SQL
                           users' passwords (as SHA-256 hashes) and open their host
    hyperdx-connections    print the HyperDX DEFAULT_CONNECTIONS JSON (viewer login)

No subcommand prints a password; only `hyperdx-connections` embeds one, because the
HyperDX app takes its connection only through that environment variable.

Design: docs/design/security-hardening/08-data-plane-and-secrets.md.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import secrets
import stat
import sys
from pathlib import Path
from typing import Mapping

ROLES = ("admin", "writer", "reader", "viewer")
# The SQL users (schema.sql) whose passwords `alter-sql` sets. `default` (admin) is an
# XML user, so its password rides the rendered override instead.
SQL_USERS = {"writer": "agent_writer", "reader": "agent_reader", "viewer": "agent_viewer"}
SERVER_XML = "50-agent-credentials.xml"
# A password becomes an HTTP basic-auth value and an environment variable, so it is
# held to a URL- and shell-safe charset; generated ones are 48 hex characters.
PASSWORD_RE = re.compile(r"^[A-Za-z0-9._~+/=-]{16,256}$")
GENERATED_BYTES = 24


class CredsError(Exception):
    """A usage or validation error, reported without a traceback."""


def default_dir(env: Mapping[str, str]) -> Path:
    explicit = env.get("AGENT_CLICKHOUSE_SECRETS", "").strip()
    if explicit:
        return Path(explicit)
    state = env.get("XDG_STATE_HOME", "").strip()
    base = Path(state) if state else Path(env.get("HOME", "~")).expanduser() / ".local/state"
    return base / "agent-seddon" / "clickhouse"


def password_path(root: Path, role: str) -> Path:
    if role not in ROLES:
        raise CredsError(f"unknown role {role!r} (use one of: {', '.join(ROLES)})")
    return root / f"{role}.password"


def server_xml_path(root: Path) -> Path:
    return root / "server" / SERVER_XML


def _refuse_if_shared(path: Path) -> None:
    mode = stat.S_IMODE(path.stat().st_mode)
    if mode & 0o077:
        raise CredsError(
            f"{path} is readable or writable by group/other (mode {mode:04o}); "
            "run `chmod go-rwx` on it"
        )


def validate_password(role: str, value: str) -> str:
    """Return the password or raise; never echo it."""
    if not PASSWORD_RE.fullmatch(value):
        raise CredsError(
            f"the {role} password is malformed: it must be 16-256 characters of "
            "A-Z a-z 0-9 . _ ~ + / = -"
        )
    return value


def read_password(root: Path, role: str) -> str:
    path = password_path(root, role)
    if not path.is_file():
        raise CredsError(f"{path} is missing; run `ch_creds.py ensure` first")
    _refuse_if_shared(path)
    return validate_password(role, path.read_text().strip())


def sha256_hex(value: str) -> str:
    return hashlib.sha256(value.encode()).hexdigest()


def render_server_xml(admin_password: str) -> str:
    return (
        "<?xml version=\"1.0\"?>\n"
        "<!-- Generated by test/clickhouse/ch_creds.py (security-hardening S16): the\n"
        "     admin (`default`) password as a SHA-256 hash. Do not edit; re-run ensure. -->\n"
        "<clickhouse>\n"
        "    <users>\n"
        "        <default>\n"
        "            <password remove=\"remove\"/>\n"
        f"            <password_sha256_hex>{sha256_hex(admin_password)}</password_sha256_hex>\n"
        "        </default>\n"
        "    </users>\n"
        "</clickhouse>\n"
    )


def alter_sql(passwords: Mapping[str, str]) -> str:
    """ALTER USER for each SQL user. Only the hash is sent, and a hash is hex, so the
    single-quoted literal cannot be broken out of."""
    lines = [
        f"ALTER USER {user} IDENTIFIED WITH sha256_hash BY '{sha256_hex(passwords[role])}' HOST ANY;"
        for role, user in SQL_USERS.items()
    ]
    return "\n".join(lines) + "\n"


def hyperdx_connections(url: str, viewer_password: str) -> str:
    return json.dumps(
        [
            {
                "name": "Local ClickHouse",
                "host": url,
                "username": SQL_USERS["viewer"],
                "password": viewer_password,
            }
        ]
    )


def _write_new(path: Path, content: str, mode: int) -> None:
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode)
    with os.fdopen(fd, "w") as f:
        f.write(content)


def ensure(root: Path) -> list[str]:
    """Create what is missing; return the roles whose password was generated."""
    if root.exists():
        if not root.is_dir():
            raise CredsError(f"{root} exists and is not a directory")
        _refuse_if_shared(root)
    else:
        root.mkdir(mode=0o700, parents=True)
        root.chmod(0o700)
    created = []
    for role in ROLES:
        path = password_path(root, role)
        if not path.exists():
            _write_new(path, secrets.token_hex(GENERATED_BYTES) + "\n", 0o600)
            created.append(role)
    passwords = {role: read_password(root, role) for role in ROLES}
    # The override holds only a hash and must be readable by the server's own uid
    # inside the container, so it is 0644 in its own directory.
    xml = server_xml_path(root)
    xml.parent.mkdir(mode=0o755, exist_ok=True)
    rendered = render_server_xml(passwords["admin"])
    # Rewrite only on change: the running container has the old inode bind-mounted.
    if not xml.exists() or xml.read_text() != rendered:
        tmp = xml.with_suffix(".tmp")
        tmp.write_text(rendered)
        tmp.chmod(0o644)
        tmp.replace(xml)
    return created


def main(argv: list[str], env: Mapping[str, str]) -> int:
    ap = argparse.ArgumentParser(prog="ch_creds.py", description=__doc__.splitlines()[0])
    ap.add_argument("--dir", type=Path, help="credentials directory (default: see --help)")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("ensure")
    p = sub.add_parser("path")
    p.add_argument("what", help="admin|writer|reader|viewer|server-xml")
    sub.add_parser("alter-sql")
    h = sub.add_parser("hyperdx-connections")
    h.add_argument("--url", required=True, help="ClickHouse HTTP URL HyperDX dials")
    args = ap.parse_args(argv)
    root = args.dir or default_dir(env)
    try:
        if args.cmd == "ensure":
            created = ensure(root)
            if created:
                print(f"ch_creds: generated {', '.join(created)} in {root}", file=sys.stderr)
        elif args.cmd == "path":
            print(server_xml_path(root) if args.what == "server-xml" else password_path(root, args.what))
        elif args.cmd == "alter-sql":
            sys.stdout.write(alter_sql({r: read_password(root, r) for r in SQL_USERS}))
        elif args.cmd == "hyperdx-connections":
            print(hyperdx_connections(args.url, read_password(root, "viewer")))
    except CredsError as e:
        print(f"ch_creds: {e}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:], os.environ))
