import '../testkit/spec.dart';

/// Access page spec (security-hardening S22): role bindings, the role catalog,
/// and tenant sessions. Positive rows cover every key stem in `access_page.dart`;
/// negative rows prove confirm dialogs and missing permissions gate the calls;
/// adversarial rows drive hostile ids, subjects and server refusals.
const accessSpec = PageSpec('access', [
  SpecRow(
    elementId: 'access.binding.item',
    caseClass: CaseClass.positive,
    name: 'loaded_bindings_render',
    description: 'ListBindings fires; each binding shows its subject and roles',
    expectedRpc: 'agent.v1.AuthService/ListBindings',
  ),
  SpecRow(
    elementId: 'access.binding.item',
    caseClass: CaseClass.boundary,
    name: 'empty_tenant_no_bindings',
    description: 'an empty tenant says so and does not crash',
    expectedRpc: 'agent.v1.AuthService/ListBindings',
  ),
  SpecRow(
    elementId: 'access.binding.item',
    caseClass: CaseClass.adversarial,
    name: 'hostile_long_subject_renders',
    description: 'a 320-character subject with bidi marks renders clipped, no overflow',
    expectedRpc: 'agent.v1.AuthService/ListBindings',
  ),
  SpecRow(
    elementId: 'access.error.retry',
    caseClass: CaseClass.negative,
    name: 'list_error_shows_retry',
    description: 'a failed ListBindings shows the offline panel',
    expectedRpc: 'agent.v1.AuthService/ListBindings',
  ),
  SpecRow(
    elementId: 'access.error.retry',
    caseClass: CaseClass.positive,
    name: 'retry_recovers',
    description: 'Retry re-lists and shows the bindings',
    expectedRpc: 'agent.v1.AuthService/ListBindings',
  ),
  SpecRow(
    elementId: 'access.error.message',
    caseClass: CaseClass.positive,
    name: 'offline_message_names_the_error',
    description: 'the offline panel names the failure',
    expectedRpc: 'agent.v1.AuthService/ListBindings',
  ),
  SpecRow(
    elementId: 'access.error.message',
    caseClass: CaseClass.negative,
    name: 'permission_denied_explains',
    description: 'a PermissionDenied load says the user may not see it',
    expectedRpc: 'agent.v1.AuthService/ListBindings',
  ),
  SpecRow(
    elementId: 'access.view.bindings',
    caseClass: CaseClass.positive,
    name: 'switch_back_to_bindings',
    description: 'returning to Bindings re-lists them',
    expectedRpc: 'agent.v1.AuthService/ListBindings',
  ),
  SpecRow(
    elementId: 'access.binding.add',
    caseClass: CaseClass.positive,
    name: 'add_binding_puts_it',
    description: 'Add → fill → Save fires PutBinding with the draft; a snack confirms',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.add',
    caseClass: CaseClass.negative,
    name: 'viewer_sees_no_edit_controls',
    description: 'with only read:binding there is no add, edit or delete',
    expectedRpc: 'agent.v1.AuthService/ListBindings',
  ),
  SpecRow(
    elementId: 'access.binding.field.id',
    caseClass: CaseClass.positive,
    name: 'id_trimmed',
    description: 'the id is sent trimmed',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.field.id',
    caseClass: CaseClass.adversarial,
    name: 'traversal_id_refused',
    description: 'an id like ../x is refused locally; nothing is sent',
  ),
  SpecRow(
    elementId: 'access.binding.field.kind',
    caseClass: CaseClass.positive,
    name: 'choose_domain_kind',
    description: 'choosing domain sends subject_kind domain',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.field.subject',
    caseClass: CaseClass.positive,
    name: 'subject_trimmed',
    description: 'the subject is sent trimmed',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.field.subject',
    caseClass: CaseClass.boundary,
    name: 'subject_capped_at_320',
    description: 'typing 321 characters sends 320',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.field.subject',
    caseClass: CaseClass.adversarial,
    name: 'control_chars_refused',
    description: 'a subject with a control character is refused locally',
  ),
  SpecRow(
    elementId: 'access.binding.role',
    caseClass: CaseClass.positive,
    name: 'roles_sent_sorted',
    description: 'the chosen roles are sent, sorted',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.role',
    caseClass: CaseClass.corner,
    name: 'catalog_unavailable_offers_builtins',
    description: 'when RoleService fails the built-in roles are still offered',
    expectedRpc: 'agent.v1.RoleService/List',
  ),
  SpecRow(
    elementId: 'access.binding.field.expires',
    caseClass: CaseClass.positive,
    name: 'expiry_days_sent',
    description: '30 days sends expires_at about 30 days out',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.field.expires',
    caseClass: CaseClass.boundary,
    name: 'expiry_over_cap_refused',
    description: '3651 days is refused locally',
  ),
  SpecRow(
    elementId: 'access.binding.field.keep',
    caseClass: CaseClass.positive,
    name: 'keep_sessions_sent',
    description: 'the keep-sessions switch sends keep_sessions',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.save',
    caseClass: CaseClass.positive,
    name: 'save_reports_signed_out_sessions',
    description: 'the snack reports how many sessions were signed out',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.cancel',
    caseClass: CaseClass.positive,
    name: 'cancel_sends_nothing',
    description: 'Cancel closes the editor without a call',
  ),
  SpecRow(
    elementId: 'access.binding.editor.error',
    caseClass: CaseClass.positive,
    name: 'missing_role_shown',
    description: 'Save with no role shows the reason; nothing is sent',
  ),
  SpecRow(
    elementId: 'access.binding.editor.error',
    caseClass: CaseClass.corner,
    name: 'last_admin_message_shown',
    description: 'a FailedPrecondition shows the server text and keeps the draft',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.editor.error',
    caseClass: CaseClass.adversarial,
    name: 'escalation_refusal_explained',
    description: 'a PermissionDenied put explains the grant rules',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.edit',
    caseClass: CaseClass.positive,
    name: 'edit_keeps_id_and_expiry',
    description: 'editing keeps the id and the old expiry unless changed',
    expectedRpc: 'agent.v1.AuthService/PutBinding',
  ),
  SpecRow(
    elementId: 'access.binding.delete',
    caseClass: CaseClass.positive,
    name: 'delete_confirmed',
    description: 'confirming fires DeleteBinding (sessions revoked by default)',
    expectedRpc: 'agent.v1.AuthService/DeleteBinding',
  ),
  SpecRow(
    elementId: 'access.binding.delete',
    caseClass: CaseClass.negative,
    name: 'delete_cancel_sends_nothing',
    description: 'cancelling the confirm sends nothing',
  ),
  SpecRow(
    elementId: 'access.binding.delete.keep',
    caseClass: CaseClass.positive,
    name: 'keep_checked_sent',
    description: 'the keep box sends keep_sessions on delete',
    expectedRpc: 'agent.v1.AuthService/DeleteBinding',
  ),
  SpecRow(
    elementId: 'access.view.roles',
    caseClass: CaseClass.positive,
    name: 'shows_roles',
    description: 'Roles lists the catalog',
    expectedRpc: 'agent.v1.RoleService/List',
  ),
  SpecRow(
    elementId: 'access.role.item',
    caseClass: CaseClass.positive,
    name: 'cards_render_with_summary',
    description: 'each card shows its grants and host-wide flag',
    expectedRpc: 'agent.v1.RoleService/List',
  ),
  SpecRow(
    elementId: 'access.role.item',
    caseClass: CaseClass.corner,
    name: 'catalog_not_served',
    description: 'an unimplemented RoleService shows the built-ins only, no add',
    expectedRpc: 'agent.v1.RoleService/List',
  ),
  SpecRow(
    elementId: 'access.role.add',
    caseClass: CaseClass.positive,
    name: 'add_role_opens_editor',
    description: 'Add role opens an empty editor',
  ),
  SpecRow(
    elementId: 'access.role.add',
    caseClass: CaseClass.negative,
    name: 'reader_sees_no_role_controls',
    description: 'with only read:role there is no add, edit or delete',
    expectedRpc: 'agent.v1.RoleService/List',
  ),
  SpecRow(
    elementId: 'access.role.field.id',
    caseClass: CaseClass.positive,
    name: 'id_sent_trimmed',
    description: 'the role id is sent trimmed',
    expectedRpc: 'agent.v1.RoleService/Put',
  ),
  SpecRow(
    elementId: 'access.role.field.id',
    caseClass: CaseClass.adversarial,
    name: 'builtin_id_refused',
    description: 'a built-in id such as operator is refused locally',
  ),
  SpecRow(
    elementId: 'access.role.field.perms',
    caseClass: CaseClass.positive,
    name: 'pairs_sent',
    description: 'action:resource lines send pairs',
    expectedRpc: 'agent.v1.RoleService/Put',
  ),
  SpecRow(
    elementId: 'access.role.field.crosses',
    caseClass: CaseClass.positive,
    name: 'host_wide_sent',
    description: 'the host-wide switch sends crosses_tenants',
    expectedRpc: 'agent.v1.RoleService/Put',
  ),
  SpecRow(
    elementId: 'access.role.save',
    caseClass: CaseClass.positive,
    name: 'actions_on_all_sent',
    description: 'action:* lines send actions_on_all',
    expectedRpc: 'agent.v1.RoleService/Put',
  ),
  SpecRow(
    elementId: 'access.role.cancel',
    caseClass: CaseClass.positive,
    name: 'role_cancel_sends_nothing',
    description: 'Cancel closes the role editor without a call',
  ),
  SpecRow(
    elementId: 'access.role.editor.error',
    caseClass: CaseClass.positive,
    name: 'mixed_shapes_refused',
    description: 'mixing action:* and action:resource is refused locally',
  ),
  SpecRow(
    elementId: 'access.role.editor.error',
    caseClass: CaseClass.adversarial,
    name: 'server_refusal_shown',
    description: 'an InvalidArgument put shows the server reason',
    expectedRpc: 'agent.v1.RoleService/Put',
  ),
  SpecRow(
    elementId: 'access.role.edit',
    caseClass: CaseClass.positive,
    name: 'edit_prefills_permissions',
    description: 'editing a * card prefills * and saves all',
    expectedRpc: 'agent.v1.RoleService/Put',
  ),
  SpecRow(
    elementId: 'access.role.delete',
    caseClass: CaseClass.positive,
    name: 'role_delete_confirmed',
    description: 'confirming fires RoleService.Delete',
    expectedRpc: 'agent.v1.RoleService/Delete',
  ),
  SpecRow(
    elementId: 'access.view.sessions',
    caseClass: CaseClass.positive,
    name: 'shows_sessions',
    description: 'Sessions lists the tenant sessions',
    expectedRpc: 'agent.v1.AuthService/ListSessions',
  ),
  SpecRow(
    elementId: 'access.session.item',
    caseClass: CaseClass.positive,
    name: 'sorted_by_last_seen',
    description: 'the most recently seen session is first; yours is marked',
    expectedRpc: 'agent.v1.AuthService/ListSessions',
  ),
  SpecRow(
    elementId: 'access.session.revoke',
    caseClass: CaseClass.positive,
    name: 'revoke_confirmed',
    description: 'confirming fires RevokeSession for that sid',
    expectedRpc: 'agent.v1.AuthService/RevokeSession',
  ),
  SpecRow(
    elementId: 'access.session.revoke',
    caseClass: CaseClass.negative,
    name: 'revoke_cancel_sends_nothing',
    description: 'cancelling the confirm sends nothing',
  ),
  SpecRow(
    elementId: 'access.session.revoke',
    caseClass: CaseClass.corner,
    name: 'revoked_session_has_no_button',
    description: 'an already revoked session cannot be revoked again',
    expectedRpc: 'agent.v1.AuthService/ListSessions',
  ),
  SpecRow(
    elementId: 'access.session.revoke',
    caseClass: CaseClass.corner,
    name: 'own_session_warns',
    description: 'revoking your own session warns that it signs you out',
  ),
  SpecRow(
    elementId: 'access.session.revoke',
    caseClass: CaseClass.adversarial,
    name: 'revoke_denied_snack',
    description: 'a PermissionDenied revoke is reported, not crashed',
    expectedRpc: 'agent.v1.AuthService/RevokeSession',
  ),
  SpecRow(
    elementId: 'access.sessions.refresh',
    caseClass: CaseClass.positive,
    name: 'refresh_relists',
    description: 'Refresh fires ListSessions again',
    expectedRpc: 'agent.v1.AuthService/ListSessions',
  ),
]);
