// @generated by `nix run .#gen-constants` from nix/constants.nix — DO NOT EDIT.
//
// Per-seam default gRPC endpoints: a unique loopback TCP port and a
// unix-domain-socket path. `nix/constants.nix` is the single source of truth;
// regenerate after editing it (`nix run .#gen-constants`). The `constants-sync`
// flake check fails if this file drifts.

/// A seam's default gRPC listen endpoints.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SeamEndpoint {
    /// Loopback TCP port, for cross-process / cross-host use.
    pub tcp_port: u16,
    /// Unix-domain-socket path, for same-host TCP-bypassing use.
    pub uds_path: &'static str,
    /// Loopback Prometheus `/metrics` port used when this seam runs as its own
    /// `agent --serve-<seam>` process (so co-located seam servers don't collide).
    pub metrics_port: u16,
}

/// Directory holding the per-seam unix domain sockets.
pub const SOCKET_DIR: &str = "/tmp/agent-seddon";

pub const PROVIDER: SeamEndpoint = SeamEndpoint {
    tcp_port: 50051,
    uds_path: "/tmp/agent-seddon/provider.sock",
    metrics_port: 9601,
};
pub const MEMORY: SeamEndpoint = SeamEndpoint {
    tcp_port: 50052,
    uds_path: "/tmp/agent-seddon/memory.sock",
    metrics_port: 9602,
};
pub const TOOLS: SeamEndpoint = SeamEndpoint {
    tcp_port: 50053,
    uds_path: "/tmp/agent-seddon/tools.sock",
    metrics_port: 9603,
};
pub const CONTEXT: SeamEndpoint = SeamEndpoint {
    tcp_port: 50054,
    uds_path: "/tmp/agent-seddon/context.sock",
    metrics_port: 9604,
};
pub const POLICY: SeamEndpoint = SeamEndpoint {
    tcp_port: 50055,
    uds_path: "/tmp/agent-seddon/policy.sock",
    metrics_port: 9605,
};
pub const SEARCH: SeamEndpoint = SeamEndpoint {
    tcp_port: 50056,
    uds_path: "/tmp/agent-seddon/search.sock",
    metrics_port: 9606,
};
pub const REPO: SeamEndpoint = SeamEndpoint {
    tcp_port: 50057,
    uds_path: "/tmp/agent-seddon/repo.sock",
    metrics_port: 9607,
};
pub const SESSION: SeamEndpoint = SeamEndpoint {
    tcp_port: 50058,
    uds_path: "/tmp/agent-seddon/session.sock",
    metrics_port: 9608,
};
pub const SCANNER: SeamEndpoint = SeamEndpoint {
    tcp_port: 50059,
    uds_path: "/tmp/agent-seddon/scanner.sock",
    metrics_port: 9609,
};
pub const REFERENCE: SeamEndpoint = SeamEndpoint {
    tcp_port: 50060,
    uds_path: "/tmp/agent-seddon/reference.sock",
    metrics_port: 9610,
};
pub const SCHEDULER: SeamEndpoint = SeamEndpoint {
    tcp_port: 50061,
    uds_path: "/tmp/agent-seddon/scheduler.sock",
    metrics_port: 9611,
};
pub const TOKENIZER: SeamEndpoint = SeamEndpoint {
    tcp_port: 50062,
    uds_path: "/tmp/agent-seddon/tokenizer.sock",
    metrics_port: 9612,
};
pub const EMBED: SeamEndpoint = SeamEndpoint {
    tcp_port: 50063,
    uds_path: "/tmp/agent-seddon/embed.sock",
    metrics_port: 9613,
};
pub const WEB: SeamEndpoint = SeamEndpoint {
    tcp_port: 50064,
    uds_path: "/tmp/agent-seddon/web.sock",
    metrics_port: 9614,
};
pub const WEB_SEARCH: SeamEndpoint = SeamEndpoint {
    tcp_port: 50065,
    uds_path: "/tmp/agent-seddon/web-search.sock",
    metrics_port: 9615,
};
pub const SANDBOX: SeamEndpoint = SeamEndpoint {
    tcp_port: 50066,
    uds_path: "/tmp/agent-seddon/sandbox.sock",
    metrics_port: 9616,
};
pub const PTY: SeamEndpoint = SeamEndpoint {
    tcp_port: 50067,
    uds_path: "/tmp/agent-seddon/pty.sock",
    metrics_port: 9617,
};
pub const FORGE: SeamEndpoint = SeamEndpoint {
    tcp_port: 50068,
    uds_path: "/tmp/agent-seddon/forge.sock",
    metrics_port: 9618,
};
pub const TASKS: SeamEndpoint = SeamEndpoint {
    tcp_port: 50069,
    uds_path: "/tmp/agent-seddon/tasks.sock",
    metrics_port: 9619,
};

/// The `agent --serve-all` gateway (not a seam — it hosts every seam).
pub const GATEWAY: SeamEndpoint = SeamEndpoint {
    tcp_port: 50100,
    uds_path: "/tmp/agent-seddon/gateway.sock",
    metrics_port: 9700,
};
