// @generated by `nix run .#gen-constants` from nix/constants.nix — DO NOT EDIT.
//
// Per-seam default gRPC endpoints: a unique loopback TCP port and a
// unix-domain-socket path. `nix/constants.nix` is the single source of truth;
// regenerate after editing it (`nix run .#gen-constants`). The `constants-sync`
// flake check fails if this file drifts.

/// A seam's default gRPC listen endpoints.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SeamEndpoint {
    /// Loopback TCP port, for cross-process / cross-host use.
    pub tcp_port: u16,
    /// Unix-domain-socket path, for same-host TCP-bypassing use.
    pub uds_path: &'static str,
}

/// Directory holding the per-seam unix domain sockets.
pub const SOCKET_DIR: &str = "/tmp/agent-seddon";

pub const PROVIDER: SeamEndpoint = SeamEndpoint {
    tcp_port: 50051,
    uds_path: "/tmp/agent-seddon/provider.sock",
};
pub const MEMORY: SeamEndpoint = SeamEndpoint {
    tcp_port: 50052,
    uds_path: "/tmp/agent-seddon/memory.sock",
};
pub const TOOLS: SeamEndpoint = SeamEndpoint {
    tcp_port: 50053,
    uds_path: "/tmp/agent-seddon/tools.sock",
};
pub const CONTEXT: SeamEndpoint = SeamEndpoint {
    tcp_port: 50054,
    uds_path: "/tmp/agent-seddon/context.sock",
};
pub const POLICY: SeamEndpoint = SeamEndpoint {
    tcp_port: 50055,
    uds_path: "/tmp/agent-seddon/policy.sock",
};
