# Rewrites the generated document's `info` block (protoc-gen-openapiv2 defaults it to
# the first merged proto's filename + "version not set"). Applied by nix/gen-openapi.nix
# so the published contract carries a real title/version and the "recommend gRPC,
# do-not-edit" guidance. jq is deterministic, so the committed doc stays diff-stable.
.info = {
  title: "Agent gRPC API — REST/JSON projection",
  version: "v1",
  description: "REST/JSON projection of the agent gRPC API, served by Envoy `grpc_json_transcoder` (docs/design/rest-openapi/). gRPC is the primary interface; REST is a low-traffic compatibility surface. @generated by `nix run .#gen-openapi` from the .proto (google.api.http) annotations — DO NOT EDIT; the openapi-sync flake check fails on drift."
}
