# nix/prometheus/default.nix
#
# Prometheus container lifecycle as Nix apps (docker) — the scraper that pulls the
# agent's `/metrics` and feeds Grafana. Mirrors the clickhouse/clickstack modules.
#
# Networking (Linux): the container runs with `--network host` so it can scrape
# the agent's loopback endpoints (`127.0.0.1:9600` + the per-seam `--serve-<seam>`
# ports). The agent binds `127.0.0.1`, which a bridged container could not reach.
# On macOS/Windows docker there is no host networking — use `host.docker.internal`
# targets instead (and drop `--network host`).
#
# `prometheus.yml` is generated from nix/constants.nix (via `versions.grpc`) so the
# scrape targets can never drift from the ports the serve processes actually bind.
{
  pkgs,
  lib,
  versions,
}:

let
  name = versions.prometheusContainerName;
  image = versions.prometheusImage;
  port = toString versions.prometheusPort;
  g = versions.grpc;

  # One scrape job per seam server. Built as an explicit-indent plain string
  # (not a `''` block) so the 2-space indentation under `scrape_configs:` survives
  # verbatim — Nix's `''` common-indent stripping would otherwise flatten it.
  seamJob =
    jobName: metricsPort:
    "  - job_name: \"${jobName}\"\n"
    + "    static_configs:\n"
    + "      - targets: [\"127.0.0.1:${toString metricsPort}\"]\n";

  seamJobs =
    seamJob "provider" g.provider.metrics_port
    + seamJob "memory" g.memory.metrics_port
    + seamJob "tools" g.tools.metrics_port
    + seamJob "context" g.context.metrics_port
    + seamJob "policy" g.policy.metrics_port
    + seamJob "search" g.search.metrics_port
    + seamJob "repo" g.repo.metrics_port
    + seamJob "gateway" g.gateway.metrics_port;

  configYml = pkgs.writeText "prometheus.yml" (
    ''
      # @generated by nix/prometheus/default.nix — edit that (targets come from
      # nix/constants.nix). A short scrape interval suits interactive local runs.
      global:
        scrape_interval: 5s
        evaluation_interval: 5s

      scrape_configs:
        # The main agent process (one-shot / REPL): `[metrics] listen` default.
        - job_name: "agent"
          static_configs:
            - targets: ["127.0.0.1:${toString versions.agentMetricsPort}"]

        # Distributed topology: each `agent --serve-<seam>` process exposes its own
        # `/metrics` (server-side seam latency). DOWN until that seam is served.
    ''
    + seamJobs
  );
in
{
  prometheus-up = pkgs.writeShellApplication {
    name = "prometheus-up";
    runtimeInputs = [
      versions.docker
      versions.curl
    ];
    text = ''
        set -euo pipefail

        if ! docker info >/dev/null 2>&1; then
          echo "prometheus-up: docker daemon not reachable — is it running?" >&2
          exit 1
        fi

        if docker ps -a --format '{{.Names}}' | grep -qx "${name}"; then
          echo "==> container '${name}' already exists; (re)starting it"
          docker start "${name}" >/dev/null
        else
          echo "==> starting Prometheus (${image})"
          # `--network host` (Linux): Prometheus listens on host :${port} and can
          # scrape the agent's 127.0.0.1 metrics ports directly.
          docker run -d \
            --name "${name}" \
            --network host \
            -v "${configYml}:/etc/prometheus/prometheus.yml:ro" \
            "${image}" >/dev/null
        fi

        echo -n "==> waiting for Prometheus to be ready"
        for _ in $(seq 1 60); do
          if curl -sf -o /dev/null "http://localhost:${port}/-/ready" 2>/dev/null; then
            echo " ready"
            break
          fi
          echo -n "."
          sleep 1
        done

        cat <<EOF

      Prometheus is up.
        UI:      http://localhost:${port}        (Status → Targets to see scrape health)
        Config:  ${configYml}

      Enable metrics in config/agent.toml ([metrics] enabled = true), run a REPL
      session or a `--serve-<seam>` process, then check Status → Targets.
        Grafana: nix run .#grafana-up
        Stop:    nix run .#prometheus-down
      EOF
    '';
  };

  prometheus-down = pkgs.writeShellApplication {
    name = "prometheus-down";
    runtimeInputs = [ versions.docker ];
    text = ''
      set -euo pipefail
      if docker ps -a --format '{{.Names}}' | grep -qx "${name}"; then
        echo "==> removing container '${name}' (data is discarded)"
        docker rm -f "${name}" >/dev/null
        echo "done"
      else
        echo "container '${name}' not found — nothing to do"
      fi
    '';
  };
}
