//! The committed OpenAPI contract must cover exactly the surface's transcoding routes.
//!
//! gap-analysis §4 / `docs/design/rest-openapi/`: `crates/agent-proto/openapi/agent.swagger.json`
//! is generated from the `.proto` `(google.api.http)` annotations by
//! `nix run .#gen-openapi`, and the `openapi-sync` flake check keeps the committed file
//! matching that generator. This test is the *other* half of the contract: it asserts
//! the committed doc's `(verb, path)` set equals the route set decoded straight from the
//! descriptor — so a generator that silently dropped (or invented) a route is caught in
//! `cargo test`, not just at Envoy load time. The two never drift because both read
//! `crates/agent-proto/openapi/agent.swagger.json` / `FILE_DESCRIPTOR_SET` respectively.
//!
//! Path templates are compared with their parameter *names* elided (`{id}` ~ `{fooId}`):
//! protoc-gen-openapiv2 emits the JSON (camelCase) field name in the template while our
//! annotations use the proto (snake_case) name, but the REST path shape is identical.

use serde_json::Value;
use std::collections::BTreeSet;

mod proto_http;
use proto_http::methods;

/// The committed contract (generated by `nix run .#gen-openapi`).
const SWAGGER: &str = include_str!("../openapi/agent.swagger.json");

/// The HTTP verbs an OpenAPI 2.0 path item can carry (everything else — e.g.
/// `parameters` — is not an operation).
const VERBS: &[&str] = &["get", "put", "post", "delete", "patch", "head", "options"];

/// Elide the parameter name inside every `{…}` so path templates compare by shape:
/// `/v1/x/{id}` and `/v1/x/{fooId}` both normalize to `/v1/x/{}`.
fn normalize(path: &str) -> String {
    let mut out = String::with_capacity(path.len());
    let mut in_brace = false;
    for c in path.chars() {
        match c {
            '{' => {
                in_brace = true;
                out.push('{');
            }
            '}' => {
                in_brace = false;
                out.push('}');
            }
            _ if in_brace => {}
            _ => out.push(c),
        }
    }
    out
}

fn parse_swagger() -> Value {
    serde_json::from_str(SWAGGER).expect("committed agent.swagger.json is valid JSON")
}

/// `(VERB, normalized-path)` for every operation the committed doc advertises.
fn swagger_routes(doc: &Value) -> BTreeSet<(String, String)> {
    let mut set = BTreeSet::new();
    let paths = doc
        .get("paths")
        .and_then(Value::as_object)
        .expect("swagger doc has a paths object");
    for (path, item) in paths {
        let item = item.as_object().expect("path item is an object");
        for verb in VERBS {
            if item.contains_key(*verb) {
                set.insert((verb.to_uppercase(), normalize(path)));
            }
        }
    }
    set
}

/// `(VERB, normalized-path)` for every route decoded straight from the descriptor.
fn descriptor_routes() -> BTreeSet<(String, String)> {
    let mut set = BTreeSet::new();
    for info in methods().values() {
        for r in &info.routes {
            set.insert((r.verb.to_string(), normalize(&r.path)));
        }
    }
    set
}

// positive — the committed artifact is a well-formed Swagger 2.0 document with paths.
#[test]
fn positive_committed_doc_is_swagger_2_with_paths() {
    let doc = parse_swagger();
    assert_eq!(
        doc.get("swagger").and_then(Value::as_str),
        Some("2.0"),
        "committed doc is not Swagger 2.0"
    );
    assert!(
        !swagger_routes(&doc).is_empty(),
        "committed doc advertises no routes"
    );
}

// positive — the doc advertises EXACTLY the descriptor's routes: no route the descriptor
// declares is missing from the doc, and the doc invents none the descriptor lacks. This
// is what would catch a generator that dropped or mangled a `google.api.http` binding.
#[test]
fn positive_openapi_routes_equal_descriptor_routes() {
    let doc = parse_swagger();
    let from_doc = swagger_routes(&doc);
    let from_desc = descriptor_routes();

    let missing: Vec<_> = from_desc.difference(&from_doc).collect();
    let extra: Vec<_> = from_doc.difference(&from_desc).collect();
    assert!(
        missing.is_empty() && extra.is_empty(),
        "OpenAPI ↔ descriptor route drift — regenerate with `nix run .#gen-openapi`.\n  \
         in descriptor but not in the doc: {missing:?}\n  \
         in the doc but not in the descriptor: {extra:?}"
    );
}

// boundary — the whole surface is covered: the doc has at least one route, and its route
// count equals the descriptor's (belt-and-braces with the set equality above, but a
// readable single-number failure if counts diverge).
#[test]
fn boundary_doc_covers_the_whole_route_surface() {
    let doc = parse_swagger();
    let n_doc = swagger_routes(&doc).len();
    let n_desc = descriptor_routes().len();
    assert!(n_desc > 0, "descriptor decoded zero routes");
    assert_eq!(
        n_doc, n_desc,
        "route count mismatch: doc has {n_doc}, descriptor has {n_desc}"
    );
}

// adversarial — the published paths are part of the wire contract: every one must be
// absolute, version-prefixed, brace-balanced, and free of `..` (the doc must never
// advertise a traversal-shaped or malformed path). Fail closed.
#[test]
fn adversarial_every_published_path_is_versioned_and_safe() {
    let doc = parse_swagger();
    let paths = doc
        .get("paths")
        .and_then(Value::as_object)
        .expect("swagger doc has a paths object");
    for path in paths.keys() {
        assert!(
            path.starts_with("/v1/"),
            "published path is not under /v1/: {path}"
        );
        assert!(!path.contains(".."), "published path contains `..`: {path}");
        assert_eq!(
            path.matches('{').count(),
            path.matches('}').count(),
            "published path has unbalanced braces: {path}"
        );
    }
}
