-- agent-config-store schema migration 0002 (PG-02): scale the `pos` write path.
--
-- v1 (0001) assigned `pos` with a global `(SELECT MAX(pos) + 1 FROM cards)`
-- subquery on every Put/CAS — a full-table aggregate that serializes all writers
-- on one hot spot as the table grows. Make `pos` a `GENERATED BY DEFAULT AS
-- IDENTITY` column so Postgres hands out the next value from an internal sequence
-- (no scan, no write-serialization point), and seed that sequence past the
-- highest existing `pos` so rows written under v1 (which hold 0..N) never collide
-- with new inserts. Add the composite index that backs `list ... ORDER BY pos`
-- scoped to (collection, tenant), turning a per-tenant listing into an index
-- range scan instead of a filter + sort.
--
-- Applied exactly once by the versioned runner (`postgres.rs`
-- `PgBackend::run_migrations`) inside one transaction; DDL is transactional in
-- Postgres, so this lands whole or rolls back. `IF NOT EXISTS` on the index keeps
-- a re-record (or an out-of-band pre-creation) harmless.

ALTER TABLE cards ALTER COLUMN pos ADD GENERATED BY DEFAULT AS IDENTITY;

-- Advance the identity sequence so the next value is one past the current
-- MAX(pos). `setval(seq, n, false)` makes the next `nextval` return `n`; on an
-- empty table MAX is NULL -> COALESCE 0 -> next value 1.
SELECT setval(
    pg_get_serial_sequence('cards', 'pos'),
    COALESCE((SELECT MAX(pos) FROM cards), 0) + 1,
    false
);

CREATE INDEX IF NOT EXISTS cards_list_idx ON cards (collection, tenant, pos);
